### PR TITLE
files for theme customisation

### PR DESCRIPTION
**Pull request by Fa7C0n**
Added files for customising our existing theme like

- removing the unwanted contents
- adding link back to the home page
- removed the top header with giant link to github
- 

will add other customisations as they are added here

### CODE REVIEW

**Comment by Fa7C0n** [comment]
@arnabdutta73 @nikitaagarwal1112 @ShenbagaRajanV @sreejasuresh007 @Rajasivaranjan Please add your suggestions for the theme customisations, I will try to address them as much as possible in this PR.

**Comment by Fa7C0n** [comment]
image

this is how the page looks with the current state of customisations

**Comment by Fa7C0n** [comment]
@sreejasuresh007 I don't know what type of help file to write because the files I have changed are from the provides theme only, I just removed some unwanted parts from there. I can link to the document I referred here to know what I did other than that can you give an example of what type of help file I need to write?

**Comment by sreejasuresh007** [comment]
I was thinking help might be required if we are just adding code so that even a layman can use these files directly in their project. Maybe a file can be added to help someone add this customization to his project.

**Comment by Fa7C0n** [comment]
@sreejasuresh007 the files I have changed in this PR won't be visible to readers in `blrgis.github.io` as raw code because these files will be consumed as a part of build process and used to customise the Theme based on our preferences.

**Pull request merged**
